openapi: 3.0.0
info:
  title: The Social CRM - Integration Specifications
  version: '1.0'
  description: >-
    The CRM and Zeoniq sytem integration


    We use API keys as the secure key to access The Social CRM.

    Please get in touch with us to request an apiKey.


    For the work flow, please prefer this diagram:
    https://crm-zeoniq.herokuapp.com/docs/the-social-payment-earn-point.pdf
  contact:
    name: Duong Nguyen
    email: nhduong29@gmail.com
servers:
  - url: 'https://thesocial.stoplight.io/mocks/thesocial/thesocial-zeoniq/2252264'
paths:
  /customer:
    get:
      summary: Get Customer Information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: &ref_3
                description: ''
                type: object
                title: Customer
                x-examples:
                  example-1:
                    cardNumber: '123456'
                    phoneNumber: '+61123456789'
                    email: test@gmail.com
                    name: User1
                    accountNumber: '123456'
                    pointBalance: 980
                    creditBalance: 985.2
                    tier: GOLD
                    vouchers:
                      - voucherID: v0123
                        voucherName: RM50 off the bill
                        value: 0
                        voucherType: Cash Voucher
                properties:
                  cardNumber:
                    type: string
                    minLength: 1
                  phoneNumber:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  accountNumber:
                    type: string
                    minLength: 1
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  tier:
                    type: string
                    minLength: 1
                  vouchers:
                    type: array
                    description: List all of vouchers that this user have
                    items: &ref_0
                      title: Voucher
                      type: object
                      description: Voucher of Customer
                      x-examples:
                        example-1:
                          voucherID: string
                          voucherName: string
                          value: 0
                          voucherType: string
                      properties:
                        voucherID:
                          type: string
                        voucherName:
                          type: string
                        value:
                          type: number
                        voucherType:
                          type: string
                        expiryDate:
                          type: string
                required:
                  - cardNumber
                  - phoneNumber
                  - email
                  - name
                  - accountNumber
                  - pointBalance
                  - creditBalance
                  - tier
              examples:
                example-1:
                  value:
                    cardNumber: '0123456'
                    phoneNumber: '+601127308562'
                    email: user@gmail.com
                    name: User Test
                    accountNumber: ACC_NUMBER001
                    pointBalance: 8000
                    creditBalance: 230
                    tier: GOLD
                    vouchers:
                      - voucherID: VOUCHER001_ACC_NUMBER001
                        voucherName: Free chicken rice
                        value: 1
                        voucherType: PRODUCT_PROMOTION
                        expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                example-2:
                  value:
                    cardNumber: '01234567'
                    phoneNumber: '+601127308562'
                    email: user1@gmail.com
                    name: User 1 Test
                    accountNumber: ACC_NUMBER002
                    pointBalance: 9000
                    creditBalance: 500
                    tier: PLATILUM
                    vouchers:
                      - voucherID: VOUCHER001_ACC_NUMBER002
                        voucherName: Free chicken rice
                        value: 1
                        voucherType: PRODUCT_PROMOTION
                        expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                      - voucherID: VOUCHER002_ACC_NUMBER002
                        voucherName: 20% off the bill
                        value: 20
                        voucherType: DISCOUNT
                        expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                      - voucherID: VOUCHER003_ACC_NUMBER002
                        voucherName: RM50 off the bill
                        value: 50
                        voucherType: CASH
                        expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: ACC-NOT-FOUND
                    message: Accound not found
      operationId: get-customer
      parameters:
        - schema:
            type: string
          in: query
          name: cardNumber
          required: true
          description: Card number of Customer
      description: Get customer informations by cardNumber
      security:
        - Authorization apiKey: []
  /submit-sale:
    post:
      summary: Submit a sale data to CRM
      operationId: post-submit-sale
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  remarks:
                    type: string
                    minLength: 1
                  pointEarned:
                    type: number
                  pointRedeemed:
                    type: number
                required:
                  - pointBalance
                  - creditBalance
                  - remarks
              examples:
                example-1:
                  value:
                    pointBalance: 80
                    creditBalance: 20
                    remarks: string
                    pointEarned: 100
                    pointRedeemed: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: SUBMIT-SALE-ERROR
                    message: Can't submit sale...
      description: >-
        POS submit the transaction info to the CRM to check status, check
        points, credit
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                receiptID:
                  type: string
                  minLength: 1
                orderID:
                  type: string
                  minLength: 1
                posNo:
                  type: string
                  minLength: 1
                  description: POS number
                billDate:
                  type: string
                  minLength: 1
                groundTotal:
                  type: number
                  description: Total price after tax
                taxAmount:
                  type: number
                  description: Total price befor tax
                tableNumber:
                  type: string
                  minLength: 1
                guests:
                  type: number
                  description: Amount of guests
                staffId:
                  type: string
                  minLength: 1
                  description: 'ID of Staft, who created this bill'
                menuItems:
                  type: array
                  description: List of items that User ordered
                  items: &ref_1
                    description: Order item
                    type: object
                    title: OrderItem
                    properties:
                      productCode:
                        type: string
                        minLength: 1
                      quantity:
                        type: number
                      price:
                        type: number
                      remarks:
                        type: string
                        minLength: 1
                      productName:
                        type: string
                      productCategory:
                        type: string
                    required:
                      - productCode
                      - quantity
                      - price
                      - productName
                      - productCategory
                outletID:
                  type: string
                  description: Outlet Name
                cardNumber:
                  type: string
                  description: Card number
                totalPrice:
                  type: number
                  description: Total price before tax
                totalDiscount:
                  type: number
                  description: Total of Discount
                vouchers:
                  type: array
                  description: List out all vouchers that user want to redeem
                  items: *ref_0
                payments:
                  type: array
                  description: List out all payment method user use to pay the bill
                  items: &ref_2
                    description: >-
                      The payment tender is the method by which a payment was
                      received. Cash, check, wire transfer, PayPal, credit
                      card...
                    type: object
                    properties:
                      tenderCode:
                        type: string
                        minLength: 1
                      tenderDesc:
                        type: string
                        minLength: 1
                      currencyCode:
                        type: string
                        minLength: 1
                      paymentAmount:
                        type: number
                    required:
                      - tenderCode
                      - tenderDesc
                      - currencyCode
                      - paymentAmount
                    title: Payment
              required:
                - receiptID
                - orderID
                - posNo
                - billDate
                - groundTotal
                - taxAmount
                - tableNumber
                - guests
                - staffId
                - menuItems
                - outletID
                - cardNumber
                - totalPrice
                - totalDiscount
            examples:
              example-1:
                value:
                  receiptID: RECEIPT_001
                  orderID: ORDER_001
                  posNo: POS_001
                  billDate: 'Tue Oct 20 2020 20:59:22 GMT+0800'
                  groundTotal: 200
                  taxAmount: 20
                  tableNumber: TABLE_001
                  guests: 3
                  staffId: STAFF_001
                  menuItems:
                    - productCode: CHICKEN_RICE_001
                      quantity: 2
                      price: 10
                      productName: Chicken rice Viet
                      productCategory: Category 1
                    - productCode: COFFE_001
                      quantity: 2
                      price: 5
                      productName: CAFE VIET
                      productCategory: Category 2
                  outletID: OUTLET_001
                  cardNumber: CARD_ID_01234
                  totalPrice: 220
                  totalDiscount: 0
                  vouchers:
                    - voucherID: VOUCHER001_ACC_NUMBER002
                      voucherName: Free chicken rice
                      value: 1
                      voucherType: PRODUCT_PROMOTION
                      expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                    - voucherID: VOUCHER002_ACC_NUMBER002
                      voucherName: 20% off the bill
                      value: 20
                      voucherType: DISCOUNT
                      expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                  payments:
                    - tenderCode: CASH
                      tenderDesc: pay with cash
                      currencyCode: MYR
                      paymentAmount: 100
                    - tenderCode: SOCIAL_CREDIT
                      tenderDesc: The credit of Social
                      currencyCode: MYR
                      paymentAmount: 20
              example-2:
                value:
                  receiptID: RECEIPT_001
                  orderID: ORDER_001
                  posNo: POS_001
                  billDate: 'Tue Oct 20 2020 20:59:22 GMT+0800'
                  groundTotal: 200
                  taxAmount: 20
                  tableNumber: TABLE_001
                  guests: 3
                  staffId: STAFF_001
                  menuItems:
                    - productCode: CHICKEN_RICE_001
                      quantity: 2
                      price: 10
                      productName: Chicken rice Viet
                      productCategory: Category 1
                    - productCode: COFFE_001
                      quantity: 2
                      price: 5
                      productName: CAFE VIET
                      productCategory: Category 2
                  outletID: OUTLET_001
                  cardNumber: CARD_ID_01234
                  totalPrice: 220
                  totalDiscount: 0
                  vouchers: []
                  payments: []
      security:
        - Authorization apiKey: []
    put:
      summary: 'Submit a sale data to CRM, Update on CRM, Close Transaction'
      operationId: put-submit-sale
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  pointEarned:
                    type: number
                  pointRedeemed:
                    type: number
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  remarks:
                    type: string
                    minLength: 1
                required:
                  - pointEarned
                  - pointRedeemed
                  - pointBalance
                  - creditBalance
                  - remarks
              examples:
                example-1:
                  value:
                    pointEarned: 123
                    pointRedeemed: 20
                    pointBalance: 859
                    creditBalance: 200
                    remarks: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                receiptID:
                  type: string
                  minLength: 1
                orderID:
                  type: string
                  minLength: 1
                posNo:
                  type: string
                  minLength: 1
                billDate:
                  type: string
                  minLength: 1
                groundTotal:
                  type: number
                taxAmount:
                  type: number
                tableNumber:
                  type: string
                  minLength: 1
                guests:
                  type: number
                staffId:
                  type: string
                  minLength: 1
                menuItems:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items: *ref_1
                payments:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: >-
                    List out all payment method user use to pay the bill.
                    Required
                  items: *ref_2
                outletID:
                  type: string
                  minLength: 1
                cardNumber:
                  type: string
                  minLength: 1
                totalPrice:
                  type: number
                totalDiscount:
                  type: number
                vouchers:
                  type: array
                  description: List out all vouchers that user want to redeem
                  items: *ref_0
              required:
                - receiptID
                - orderID
                - posNo
                - billDate
                - groundTotal
                - taxAmount
                - tableNumber
                - guests
                - staffId
                - menuItems
                - payments
                - outletID
                - cardNumber
                - totalPrice
                - totalDiscount
            examples:
              example-1:
                value:
                  receiptID: RECEIPT_001
                  orderID: ORDER_001
                  posNo: POS_001
                  billDate: 'Tue Oct 20 2020 20:59:22 GMT+0800'
                  groundTotal: 200
                  taxAmount: 20
                  tableNumber: TABLE_001
                  guests: 3
                  staffId: STAFF_001
                  menuItems:
                    - productCode: CHICKEN_RICE_001
                      quantity: 2
                      price: 10
                      productName: Chicken rice Viet
                      productCategory: Category 1
                    - productCode: COFFE_001
                      quantity: 2
                      price: 5
                      productName: CAFE VIET
                      productCategory: Category 2
                  outletID: OUTLET_001
                  cardNumber: CARD_ID_01234
                  totalPrice: 220
                  totalDiscount: 0
                  vouchers:
                    - voucherID: VOUCHER001_ACC_NUMBER002
                      voucherName: Free chicken rice
                      value: 1
                      voucherType: PRODUCT_PROMOTION
                      expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                    - voucherID: VOUCHER002_ACC_NUMBER002
                      voucherName: 20% off the bill
                      value: 20
                      voucherType: DISCOUNT
                      expiryDate: 'Tue Oct 20 2020 20:46:21 GMT+0800'
                  payments:
                    - tenderCode: CASH
                      tenderDesc: pay with cash
                      currencyCode: MYR
                      paymentAmount: 100
                    - tenderCode: SOCIAL_CREDIT
                      tenderDesc: The credit of Social
                      currencyCode: MYR
                      paymentAmount: 20
              example-2:
                value:
                  receiptID: RECEIPT_001
                  orderID: ORDER_001
                  posNo: POS_001
                  billDate: 'Tue Oct 20 2020 20:59:22 GMT+0800'
                  groundTotal: 200
                  taxAmount: 20
                  tableNumber: TABLE_001
                  guests: 3
                  staffId: STAFF_001
                  menuItems:
                    - productCode: CHICKEN_RICE_001
                      quantity: 2
                      price: 10
                      productName: Chicken rice Viet
                      productCategory: Category 1
                    - productCode: COFFE_001
                      quantity: 2
                      price: 5
                      productName: CAFE VIET
                      productCategory: Category 2
                  outletID: OUTLET_001
                  cardNumber: CARD_ID_01234
                  totalPrice: 220
                  totalDiscount: 0
                  vouchers: []
                  payments:
                    - tenderCode: CASH
                      tenderDesc: pay with cash
                      currencyCode: MYR
                      paymentAmount: 100
        description: ''
      description: >-
        THIS CALL TO CLOSE THE TRANSACTION, FINISH PAYMENT PROCESS.


        POS submit the transaction info to the CRM to update point, credit,
        payment history AND CLOSE TRANSACTION!

        For this API, If customer using any vouchers, you need to send it belong
        to vouchers array. The same for the payments, you have to send all the
        payment method that used in this transaction.
      security:
        - Authorization apiKey: []
      parameters: []
  /redeem-voucher:
    post:
      summary: Redeem the voucher
      operationId: post-redeem-voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  pointEarned:
                    type: integer
                  pointRedeemed:
                    type: number
                  voucher: *ref_0
                  customer: *ref_3
                  product: *ref_1
                required:
                  - pointBalance
                  - creditBalance
                  - pointEarned
                  - pointRedeemed
              examples:
                example-1:
                  value:
                    pointBalance: 100
                    creditBalance: 100
                    pointEarned: 1
                    pointRedeemed: 10
                    voucher:
                      voucherID: VOUCHER001_ACC_NUMBER002
                      voucherName: CHICKEND RICE VOUCHER
                      value: 0
                      voucherType: PRODUCT_PROMOTION
                      expiryDate: string
                    customer:
                      cardNumber: string
                      phoneNumber: string
                      email: string
                      name: string
                      accountNumber: string
                      pointBalance: 0
                      creditBalance: 0
                      tier: string
                    product:
                      productCode: CHICKEN_RICE
                      quantity: 1
                      price: 100
                      remarks: USED BY THIS VOUCHER
                      productName: Chicken rice Viet
                      productCategory: Cate 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: error
                    message: product_not_found
      description: Validate Voucher information from CRM
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                voucherID:
                  type: string
                  minLength: 1
                receiptID:
                  type: string
                  minLength: 1
                orderID:
                  type: string
                  minLength: 1
                posNo:
                  type: string
                  minLength: 1
                billDate:
                  type: string
                  minLength: 1
                tableNumber:
                  type: string
                  minLength: 1
                staffId:
                  type: string
                  minLength: 1
                outletID:
                  type: string
                  minLength: 1
              required:
                - voucherID
                - receiptID
                - posNo
                - billDate
                - staffId
                - outletID
            examples:
              example-1:
                value:
                  voucherID: VOUCHER001_ACC_NUMBER002
                  receiptID: string
                  orderID: RECEIPT_001
                  posNo: POS_001
                  billDate: 'Tue Oct 20 2020 20:59:22 GMT+0800'
                  tableNumber: TABLE_001
                  staffId: STAFF_001
                  outletID: OUTLET_001
        description: ''
      security:
        - Authorization apiKey: []
    put:
      summary: 'Redeem Voucher, Update in CRM, Close transaction'
      operationId: put-redeem-voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pointBalance:
                    type: number
                  creditBalance:
                    type: number
                  pointEarned:
                    type: number
                  pointRedeemed:
                    type: number
                  voucher: *ref_0
                  customer: *ref_3
                  product: *ref_1
              examples:
                example-1:
                  value:
                    pointBalance: 100
                    creditBalance: 100
                    pointEarned: 1
                    pointRedeemed: 10
                    voucher:
                      voucherID: VOUCHER001_ACC_NUMBER002
                      voucherName: CHICKEND RICE VOUCHER
                      value: 0
                      voucherType: PRODUCT_PROMOTION
                      expiryDate: string
                    customer:
                      cardNumber: string
                      phoneNumber: string
                      email: string
                      name: string
                      accountNumber: string
                      pointBalance: 0
                      creditBalance: 0
                      tier: string
                    product:
                      productCode: CHICKEN_RICE
                      quantity: 1
                      price: 100
                      remarks: USED BY THIS VOUCHER
                      productName: Chicken rice Viet
                      productCategory: Cate 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: string
                    message: string
      security:
        - Authorization apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                voucherID:
                  type: string
                  minLength: 1
                receiptID:
                  type: string
                  minLength: 1
                orderID:
                  type: string
                  minLength: 1
                posNo:
                  type: string
                  minLength: 1
                billDate:
                  type: string
                  minLength: 1
                tableNumber:
                  type: string
                  minLength: 1
                staffId:
                  type: string
                  minLength: 1
                outletID:
                  type: string
                  minLength: 1
              required:
                - voucherID
                - receiptID
                - orderID
                - posNo
                - billDate
                - tableNumber
                - staffId
                - outletID
            examples:
              example-1:
                value:
                  voucherID: VOUCHER001_ACC_NUMBER002
                  receiptID: string
                  orderID: RECEIPT_001
                  posNo: POS_001
                  billDate: 'Tue Oct 20 2020 20:59:22 GMT+0800'
                  tableNumber: TABLE_001
                  staffId: STAFF_001
                  outletID: OUTLET_001
      description: Redeem Voucher information from CRM
    get:
      summary: Validate Voucher
      operationId: get-redeem-voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: *ref_0
              examples:
                example-1:
                  value:
                    voucherID: string
                    voucherName: string
                    value: 0
                    voucherType: string
                    expiryDate: string
      description: Validate Voucher information from CRM
      parameters:
        - schema:
            type: string
          in: query
          required: true
          name: voucherID
  /redeem-credit:
    post:
      summary: Use Credit
      operationId: post-redeem-credit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  'acceptedCreditAmount ':
                    type: number
                  creditBalance:
                    type: number
                  rejectedCreditAmount:
                    type: number
              examples:
                example-1:
                  value:
                    'acceptedCreditAmount ': 100
                    creditBalance: 200
                    rejectedCreditAmount: 0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errorCode:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                required:
                  - errorCode
                  - message
              examples:
                example-1:
                  value:
                    errorCode: ERROR
                    message: Error mesage...
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cardNumber:
                  type: string
                creditAmount:
                  type: number
            examples:
              example-1:
                value:
                  cardNumber: '0123456'
                  creditAmount: 100
        description: ''
      security:
        - Authorization apiKey: []
      description: >-
        This API just to get the credit info when user want to pay with credit.

        To update in our CRM, you need to add the to payments array in PUT
        /submit-sale
  /health-check:
    get:
      summary: CRM heath check
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - FAILED
                      - OK
              examples:
                example-1:
                  value:
                    status: OK
                example-2:
                  value:
                    status: FAILED
      operationId: get-health-check
      security:
        - Authorization apiKey: []
      description: This API use for check the CRM is online or not.
components:
  schemas:
    Customer: *ref_3
    Payment: *ref_2
    OrderItem: *ref_1
    Voucher: *ref_0
  securitySchemes:
    Authorization apiKey:
      name: apiKey
      type: apiKey
      in: header
      description: >-
        Please get in touch with us to request a apiKey. You have to send this
        key in every request to access CRM
security:
  - Authorization with Bearer type: []
